/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.seveniu.consumer.remote.thrift;


import org.apache.thrift.TEnum;

public enum TaskStatus implements TEnum {
  WAIT(0),
  RUNNING(1),
  STOP(2);

  private final int value;

  private TaskStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static TaskStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return WAIT;
      case 1:
        return RUNNING;
      case 2:
        return STOP;
      default:
        return null;
    }
  }
}
